/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
      textPrimary: "#6A6B87",
      textSecondary: "#3F405B",
      textTertiary: "#3F405B",
      textQuaternary: "#3F405B",
      textQuinary: "#6A6B87",
      textSenary: "#FFFFFF",
      textSeptenary: "#9998A0",
      textOctonary: "#999BAB",
      textNonary: "#FFFFFF",
      textDenary: "#E7E5FF",
      textPrimaryVariant: "#E7E5FF",
      textTertiaryVariant: "#635BFE",
      textQuaternaryVariant: "#6A6B87",
      textQuinaryVariant: "#635BFE",
      textSecondaryVariant: "#6A6B87",
      textSenaryVariant: "#9998A0",
      textSeptenaryVariant: "#635BFE",
      textOctonaryVariant: "#6A6B87",
      textNonaryVariant: "#3F405B",
      textDenaryVariant: "#635BFE",

      //background
      bgPrimary: "#392F6B",
      bgSecondary: "#F9F9FE",
      bgTertiary: "#2D1959",
      bgQuaternary: "#FFFFFF",
      bgQuinary: "#FFFFFF",
      bgOctonary: "#F2EFFC",
      bgSenary: "#FFFFFF",
      bgSeptenary: "#FFFFFF",
      bgNonary: "#E8E7EA",
      bgDenary: "#CDCCD0",
      bgPrimaryVariant: "#2E2446",
      bgSecondaryVariant: "#E8E7EA",
      bgTertiaryVariant: "#635BFE",
      bgQuaternaryVariant: "#392F6B",

      //button
      btnPrimary: "#6A6B87",
      btnSecondary: "#FFFFFF",
      btnTertiary: "#635BFE",
      btnQuaternary: "#C1BFDF",
      btnQuinary: "#E8E7EA",
      btnOctonary: "#FFAF30",
      btnSenary: "#3F405B",
      btnSeptenary: "#E7E5FF",
      btnNonary: "#6A6B87",
      btnDenary: "#E7E5FF",

      //interface
      ifPrimary: "#DDD3FD",
      ifSecondary: "#E7E5FF",
      ifTertiary: "#FFFFFF",
      ifQuaternary: "#E7E5FF",
      ifQuinary: "#635BFE",
      ifSenary: "#FFFFFF",
      ifSeptenary: "#2E2446",
      ifOctonary: "#D9204C",
      ifNonary: "#2AAA5E",
      ifDenary: "#0D0B2B",
      ifPrimaryVariant: "#2E2446",
      //indicator
      ifIndicatorSecondary: "#DDD3FD",

      //border
      borderPrimary: "#C1BFDF",
      borderSecondary: "#F2EFFC",
      borderTertiary: "#E8E7EA",
      borderQuaternary: "#C1BFDF",
      borderQuinary: "#1A1721",
      borderSenary: "#E7E5FF",
      borderSeptenary: "#E7E5FF",
      borderOctonary: "#ffffff",
      borderNonary: "#E0DFEF",
      borderDenary: "#3E3356",
      borderPrimaryVariant: "#E7E5FF",

      //svg
      rightArrow: "#6A6B87",
      currencyIcon: "#635BFE",
      copyPrimary: "#3F405B",
      mailIcon: "#6A6B87",
      userIcon: "#635BFE",
      verticalPrimary: "#E0DFEF",
      filePrimary: "#9998A0",
      tabIconUnfocused: "#898989",
      drawerIconUnfocused: "#2D1959",
      switchIcon: "#E7E5FF",
      receivedRequestIcon: "#635BFE",

      //same value
      cornflowerBlue: "#635BFE",
      white: "#FFFFFF",
      sunshade: "#FFAF30",
      snuff: "#E0DFEF",
      mischka: "#E8E7EA",
      bastille: "#1A1721",
      gunPowder: "#3F405B",
      stormGray: "#6A6B87",
      green: "#5DC888",
      jacarta: "#392F6B",
      manatee: "#9998A0",
      whisper: "#F5F6FA",
      martinique: "#2E2446",
      lavenderGray: "#C1BFDF",
      ceriseRed: "#E43E66",
      haiti: "#0D0B2B",
    },
      fontFamily: {
        GilroyThin: ["GilroyThin"],
        GilroyLight: ["GilroyLight"],
        GilroyRegular: ["GilroyRegular"],
        GilroyMedium: ["GilroyMedium"],
        GilroySemiBold: ["GilroySemiBold"],
        GilroyBold: ["GilroyBold"],
        GilroyHeavy: ["GilroyHeavy"],
        GilroyBlack: ["GilroyBlack"],
      },
    },
  },
  plugins: [],
};
